### ISSUE TITLE
Archive failed, error: exit status 65

### ISSUE THREAD

**Issue by darko55555** [bitrise-steplib/steps-xcode-archive#127]
I presume this has been answered a couple of times but I seem to have this error repeatedly although my certificate and provisioning profile are valid (green marks on both), and my workflow step uses "always latest". It builds it successfully with production profile, but won't with development. I've checked multiple times for the validity of my certificates and profiles, even made new ones.

**Comment by bitce** [comment]
Hi @darko55555 !

Sorry to hear about the inconveniences! Could you send us a log file or build URL for looking into please?

**Comment by darko55555** [comment]
hey @bitce I've managed to debug it, looking into the log I saw it used my old provisioning profile even thought the new one was set on workflow. I figured it probably has to propagate through few systems and tried it the next day and it worked like a charm :)

**Comment by bitce** [comment]
That's great, nice one @darko55555  glad to hear it!

**Comment by trancelife** [comment]
Hello!
i have the same issue
[raw-xcodebuild-output.log](https://github.com/bitrise-io/steps-xcode-archive/files/2375067/raw-xcodebuild-output.log)

**Comment by bitce** [comment]
Hi @trancelife!

Based on the log it seems that you have specified a 'Distribution' export type but your profile is signed for Development. Is that correct?

To provide assistance, please send us a log file or a URL to the build as well, preferably on our on site chat :)

**Comment by trancelife** [comment]
thanks for the help! Everything is working

**Comment by bitce** [comment]
@trancelife That's awesome! Good job 😉

**Comment by smmcdonald** [comment]
I am having this issue as well. I can archive and export successfully on my local machine, but the archive fails in both codesigndoc and in the XCode build and archive step.

`Error: failed to run xcodebuild command, error: exit status 65`

[raw-xcodebuild-output.log](https://gist.github.com/smmcdonald/a90a4487b2c2f6e11ad0af591cd67116)

**Comment by fehersanyi-bitrise** [comment]
Hello @smmcdonald 👋

Could you please send us the url of this build? So I can check out the logs, and the raw logs fully as well? 🙃

**Comment by smmcdonald** [comment]
I found out it was because we are using the Legacy Build System in our project workspace settings. Switching over to the new build system will allow xcodebuild archive to run successfully. This appears to be an issue with Apple's Xcode CLI, but that doesn't help those of us who still run on the legacy build system.

**Comment by torodavit** [comment]
Hello i have issue: Archive failed, error: exit status 65
please see log 

[a5c673959644b2c7.log](https://github.com/bitrise-steplib/steps-xcode-archive/files/3422227/a5c673959644b2c7.log)

**Comment by bitce** [comment]
Hi @torodavit! I just realized we didn't make this clear earlier, an exit status message isn't telling as much, your issue seems to be completely unrelated to any of the likes of those mentioned above.

I see you have a linker error, which is unfortunately also can be caused by a number of things. Initially please check this: https://devcenter.bitrise.io/troubleshooting/frequent-ios-issues/#works-in-local-but-not-on-bitriseio
​
And possibly delete your DerivedData locally and try to rebuild on your computer, the issue could surface there just the same.

**Comment by anismansuri63** [comment]
I do have a same issue. I've attached the log.
Can you look at this and tell me what I'm missing.
[a55dc2b0bd2bd4a9.log](https://github.com/bitrise-steplib/steps-xcode-archive/files/3920149/a55dc2b0bd2bd4a9.log)
