### ISSUE TITLE
Bug with non-standard characters

### ISSUE THREAD

**Issue by soshman** [bitrise-steplib/steps-xcode-archive#143]
I've encountered a bug, when this step tries to find a scheme containing Polish character.

Exporting ipa from the archive...
Exporting ipa with ExportOptions.plist
No custom export options content provided, generating export options...
export-method specified: app-store
scheme Gdańsk not found in Gdańsk

Gdańsk is the name of polish city. :)
In Polish language there are some extra letters like: ą ę ń ó ś ć etc.
This step seems to not support them. Building locally with XCode works fine even with usage of same console command. After replacing ń with n everything works fine.

**Comment by BirmacherAkos** [comment]
Hi!

Thanks for the issue report.
I will create a card for the Tooling Team to fix it.

**Comment by BirmacherAkos** [comment]
Hi!

Which operating system/version do you use?

---

It seems the problem is caused by the different representations of the `ń` character in different operating systems.

The step compares the scheme `Gdańsk` name provided by input and the `Gdańsk.xcscheme` file, which is located in the `.xcodeproj/xcshareddata/`.
https://github.com/bitrise-io/steps-xcode-archive/blob/afcaa92c17125692aeec605cc907cec1a8212f0f/vendor/github.com/bitrise-tools/xcode-project/xcodeproj/xcodeproj.go#L192

Sadly because of the difference in the representation of the ń character they are not the same
(Even with the same language setting: `en_US.UTF-8`):
![asc](https://user-images.githubusercontent.com/37296013/52263922-b7c7bb80-2930-11e9-8d0a-900bffed30b6.png)

![screenshot 2019-02-04 at 14 56 58](https://user-images.githubusercontent.com/37296013/52264257-74218180-2931-11e9-9268-1cb9d018478f.png)


-----

We will release the Mojave for the Xcode stacks in the near future.
I think it will resolve this issue.

**Comment by soshman** [comment]
I'm not quite sure which operating system it was, because I use both my PC and MAC to edit my workflow.
However it was newest version of Windows 10 or newest version of MacOS.

Thank you for response. :)

**Comment by BirmacherAkos** [comment]
Hi @soshman !

Today we will release a new patch [2.4.20](https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.4.20) for the step, which should fix the issue.

Happy Building 🚀
