### ISSUE TITLE
Catalyst app can't be correctly parsed

### ISSUE THREAD

**Issue by el-hoshino** [bitrise-steplib/steps-xcode-archive#180]
Hi

I recently updated my project to use Catalyst, and since then this step starts to produce this `Failed to parse archive, error: Info.plist not exists at: XXX.app/Info.plist` error.

I tried to archive my project locally and found that the Info.plist is actually at `XXX.app/Contents/Info.plist`, or actually all files are now placed under `Contents` folder, which caused the step failing to parse.

**Comment by el-hoshino** [comment]
BTW here's the correct Info.plist file path 😄 
<img width="609" alt="スクリーンショット 2020-03-24 12 56 56" src="https://user-images.githubusercontent.com/3942121/77387993-44059e00-6dd2-11ea-89c5-2b396913c1b5.png">

**Comment by bitce** [comment]
Hi @el-hoshino,

Sorry to hear about the issue. Please include a build URL we can take a look at here!

**Comment by el-hoshino** [comment]
@bitce Please check the build here: https://app.bitrise.io/build/5914b37fe959ac5a

**Comment by mefiblogger** [comment]
Hi 👋 @el-hoshino,

First of all, thank your for your patience! I have some good news: our team fixed the issue and I'd like to provide some context and details about it.

Since version  [2.8.0](https://github.com/bitrise-steplib/steps-xcode-archive/releases/tag/2.8.0), we add the `-destination` flag to the `xcodebuild` call, to make sure the step builds an iOS or tvOS project.

The root-cause was that the step built a macOS archive, which has slightly different file structure from an iOS archive.

This change also solves this issue partially: [#180 - Catalyst app can't be correctly parsed](https://github.com/bitrise-steplib/steps-xcode-archive/issues/180)

Version 2.8.0 parses the given project and determines the destination flag value, based on the `SDKROOT` build settings.

This new version introduced an issue, by the invalid expectation of having `SDKROOT` build settings as a project level build settings:

- https://github.com/bitrise-steplib/steps-xcode-archive/issues/184
- https://github.com/bitrise-steplib/steps-xcode-archive/issues/185.

In version [2.8.1](https://github.com/bitrise-steplib/steps-xcode-archive/releases/tag/2.8.1), we use the target build settings returned by `xcodebuild -showBuildSettings` to get the `SDKROOT` value.

**I close this issue as the latest release should fix it. If you need more info or help, just open a new issue or get in touch with our Support Team.**

Thanks and happy building 🚀 
Mefi
