### ISSUE TITLE
Build fails "No file found at path: /Users/vagrant/git/contents.xcworkspacedata"

### ISSUE THREAD

**Issue by kndl22** [bitrise-steplib/steps-xcode-archive#193]
Hi,

My build fails with error:

`Failed to open project: /Users/vagrant/git: could not get scheme (release) from path (/Users/vagrant/git): No file found at path: /Users/vagrant/git/contents.xcworkspacedata`
`xcode-archive@2 (exit code: 1) `

Full log:

```
+------------------------------------------------------------------------------+

| (9) xcode-archive@2                                                          |
+------------------------------------------------------------------------------+
| id: xcode-archive                                                            |
| version: 2.8.5                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-06-30T18:45:14Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[18:45:15]  * [OK] Step dependency (xcode) installed, available. 
Configs:
- ExportMethod: ad-hoc
- UploadBitcode: true
- CompileBitcode: true
- ICloudContainerEnvironment: 
- TeamID: 
- UseDeprecatedExport: false
- ForceTeamID: 
- ForceProvisioningProfileSpecifier: 
- ForceProvisioningProfile: 
- ForceCodeSignIdentity: 
- CustomExportOptionsPlistContent: 
- OutputTool: xcpretty
- Workdir: /Users/vagrant/git
- ProjectPath: .
- Scheme: release
- Configuration: 
- OutputDir: /Users/vagrant/deploy
- IsCleanBuild: false
- XcodebuildOptions: 
- DisableIndexWhileBuilding: true
- ExportAllDsyms: true
- ArtifactName: release
- VerboseLog: true
- CacheLevel: swift_packages
step determined configs:
- xcodebuildVersion: Xcode 11.5 (Build version 11E608c)
Checking if output tool (xcpretty) is installed
- xcprettyVersion: 0.3.0
```

**Comment by non-binary** [comment]
Hi @kndl22,

Can you please provide a link to your build and enable support access in project settings?

**Comment by kndl22** [comment]
Hi @non-binary ,
Support access enabled, and the build is:
https://app.bitrise.io/build/579d9a3e0cd707d8#?tab=log

**Comment by dipkasyap** [comment]
I am getting same issue .

**Comment by kndl22** [comment]
Issue solved when setting **Project (or Workspace) path** to
`$BITRISE_PROJECT_PATH/ios/Runner.xcworkspace/`

This happens probably because the flutter project structure is bit different.

**Comment by rovkinmax** [comment]
I try $BITRISE_PROJECT_PATH/ios/Runner.xcworkspace/  but still the same issue
Runner.xcworkspace exist in git

**Comment by mohithuria2608** [comment]
Hey @kndl22 , can you pls explain the problm in detail.

**Comment by godrei** [comment]
Hi @kndl22 ,
sorry for the late response!

I think the original issue here is an incorrect configuration:
The `ProjectPath` input should point to an Xcode project (`.xcodeproj`) or workspace (`.xcworkspace`) path, described in the [step.yml](https://github.com/bitrise-steplib/steps-xcode-archive/blob/master/step.yml#L62-L68), but not validated during the step input parsing so that the step fails later in case of an invalid project path.

In version [3.2.3](https://github.com/bitrise-steplib/steps-xcode-archive/releases/tag/3.2.3) we introduced more validation on the `ProjectPath` input so that the step will fail early in case of incorrect configuration.

I'll close this issue, but if you need more info/help just let us know by opening a new one!
