### ISSUE TITLE
Xcode Archive & Export for iOS failed with bundle install failed for Xcode 14.2 on M1

### ISSUE THREAD

**Issue by harish-narra** [bitrise-steplib/steps-xcode-archive#324]
### Troubleshooting

- [ ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.2.3
- Is the issue reproducible with the latest version? YES / NO
- Does the issue happen sporadically, or every time? SPORADIC / EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES / NO / NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

<img width="1533" alt="Screenshot 2023-07-10 at 3 55 25 PM" src="https://github.com/bitrise-steplib/steps-xcode-archive/assets/88128887/670d1e9b-dc45-4ff3-b9da-af38b2c50b01">

### Bitrise info

- Build URL: _Please share the build URL with us._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

1. Triggerd build from bitrise
2. Archieve failed

**Comment by BenHurMartins** [comment]
+1

I am getting the same error, works locally with Xcode  with the same version, but it doesn't works in Bitrise. I am pretty new with Bitrise so I didn't find the logs yet.



C/C @sehri18

**Comment by harish-narra** [comment]
@BenHurMartins am able to generate the build last week, but from yesterday onwards getting this issue, if anything found, please post here

**Comment by gustavoMarquezRefera** [comment]
same issue here, no fix so far

**Comment by harish-narra** [comment]
any update here?

**Comment by fcastaneda9725** [comment]
I've faced the same issue. I will share how I solved it.

The status error 65 is too general, you will need to look over the logs but I think you do it in your local environment, up in the logs you will find the real error that is preventing the bundle script from running.
In my case:

- The first error was using `pnpm` but was solved using `@rnx-kit/metro-resolver-symlinks`
- Second error was missing dev babel dependencies like `@babel/plugin-proposal-nullish-coalescing-operator` or `@babel/plugin-transform-arrow-functions` used by one of my libraries

At this point, the local archive was working, but now still having the issue with the Bitrise archive step.

Found out that our mono repo had missing dependencies at the moment to archive, so I had to add some extra command lines for my `Script` step remove some dependencies and install again during a new build with [Turbo](https://turbo.build/pack) and the problem was solved.

Make sure you have your script right under `ProjectName -> Build Phases -> Bundle React Native code and images`:
```
set -e

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
````
I know that my solution was particular, but I can suggest you go deeper into the logs and you will find the real error that it's preventing `react-native-xcode.sh` to run.

**Comment by psvnanda** [comment]
+1. Is there any proposed workaround?

**Comment by bsamban** [comment]
Is there any fix for this issue ?

**Comment by RichardLima** [comment]
In my case, I fixed it after analyzing: xcodebuild-archive.log, and identified that the bitrise machine started to use an updated node version and that it has the problem: openssl-legacy-provider. :)

**Comment by sufyansalim** [comment]
any update on this issue?

**Comment by sufyansalim** [comment]
> In my case, I fixed it after analyzing: xcodebuild-archive.log, and identified that the bitrise machine started to use an updated node version and that it has the problem: openssl-legacy-provider. :)

how can i do that i new to bitrise?

**Comment by RichardLima** [comment]
@sufyansalim Workflow tab > choose your workflow > after the xcode archive step add the "Deploy to bitrise.io" step > save > run your failed workflow again > after finishing/failing > enter your build > artifacts > xcodebuild-archive.log
